image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - javadoc
  - upload
  - release
  - scheduled-tag

build:
  stage: build
  - if: '$CI_PIPELINE_SOURCE == "schedule"'
    when: never
  - if: '$CI_COMMIT_BRANCH == "master"'
    when: never
  - if: $CI_COMMIT_TAG
    when: never
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

build-weekly:
  stage: build
  rules:
    - if: '$TYPE == "snapshot"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  script:
    - gradle --build-cache assemble
    - mv "build/libs/Idle theme park world.jar" .
    - mv "./Idle theme park world.jar" "./ITPW.jar"
  artifacts:
    name: "Build$(date +\"%Y%m%d\")"
    paths:
      - ITPW.jar
    expire_in: 1 week


build-master:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: $CI_COMMIT_TAG
  script: 
    - gradle --build-cache assemble
    - mv "build/libs/Idle theme park world.jar" .
    - mv "./Idle theme park world.jar" "./ITPW.jar"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    name: 'Build-$CI_COMMIT_REF_NAME'
    paths:
      - ITPW.jar
    expire_in: 1 day


test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
